# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Teach With Science
tagline:             'Read the Latest Research Without Reading the Latest Research'
description:         'Read the Latest Research Without Reading the Latest Research'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Derek Hanson
  url:               
  email:             teachwithscience@gmail.com

# Custom vars
version:             1.0.0
